Repository Financial-Times/x-dash, pull requests merged in 2018-09, with the labels that each got.

#168 Added new update-snapshots command to makefile
  makefile
  tools/x-docs/src/docs/guides/components/setup.md
Labels: bug, housekeeping

#109 add fetchMock property to story modules
  package.json
  tools/x-docs/src/docs/guides/components/setup.md
  tools/x-workbench/.storybook/build-story.js
Labels: enhancement

#165 enzyme tests for x-increment & x-interaction; document test strategy
  __tests__/__snapshots__/snapshots.test.js.snap
  components/x-increment/__tests__/x-increment.test.jsx
  components/x-increment/package.json
  components/x-increment/src/Increment.jsx
  components/x-increment/stories/async.js
  components/x-increment/stories/index.js
  components/x-increment/stories/knobs.js
  components/x-interaction/__tests__/x-interaction.test.jsx
  components/x-interaction/package.json
  components/x-interaction/src/Hydrate.jsx
  components/x-interaction/src/Interaction.jsx
  components/x-interaction/src/InteractionClass.jsx
  components/x-interaction/src/InteractionRender.jsx
  components/x-interaction/src/InteractionSSR.jsx
  jest.config.js
  packages/x-babel-config/index.js
  packages/x-babel-config/jest.js
  packages/x-babel-config/package.json
  packages/x-rollup/package.json
  packages/x-rollup/src/babel-config.js
  packages/x-test-utils/enzyme.js
  packages/x-test-utils/package.json
  tools/x-docs/src/docs/guides/components/cookbook/testing.md
Labels: component, documentation, housekeeping

#180 fix x-interaction state resetting
  components/x-interaction/__tests__/x-interaction.test.jsx
  components/x-interaction/src/InteractionClass.jsx
Labels: bug, component
