Repository Financial-Times/x-dash, pull requests merged in 2018-10, with the labels that each got.

#170 triggering x-interaction actions externally, fixes #163
  components/x-increment/__tests__/x-increment.test.jsx
  components/x-increment/src/Increment.jsx
  components/x-interaction/__tests__/x-interaction.test.jsx
  components/x-interaction/readme.md
  components/x-interaction/src/Hydrate.jsx
  components/x-interaction/src/HydrationData.jsx
  components/x-interaction/src/Interaction.jsx
  components/x-interaction/src/InteractionClass.jsx
  components/x-interaction/src/InteractionRender.jsx
  components/x-interaction/src/InteractionSSR.jsx
  components/x-interaction/src/concerns/serialiser.js
  components/x-interaction/src/concerns/symbols.js
  packages/x-handlebars/index.js
  tools/x-ssr-demo/index.js
  tools/x-ssr-demo/package.json
  tools/x-ssr-demo/src/index.js
  tools/x-ssr-demo/views/index.html
Labels: component, documentation, enhancement

#184 Include documentation for mocking http requests
  docs/components/stories.md
Labels: documentation

#200 prevent accidental package-locking
  .npmrc
Labels: housekeeping

#211 Add isPodcast indicator
  components/x-teaser/Props.d.ts
  components/x-teaser/readme.md
  components/x-teaser/stories/knobs.js
Labels: component

#209 Add audio to content type
  components/x-teaser/Props.d.ts
Labels: component
